apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethink
spec:
  selector:
    matchLabels:
      app: rethink
  replicas: 1
  template:
    metadata:
      labels:
        app: rethink
    spec:
      containers:
      - name: rethink
        image: docker.io/rethinkdb:2.4.2
        ports:
        - containerPort: 28015
        - containerPort: 29015
        - containerPort: 8080
          name: web

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: rethink
  ports:
  - name: web
    port: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rethink-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: database
            port:
              name: web
